language : node_js

node_js:
  # - "6"
  - "8"
  - "10"
  # - "11" TODO: add 11 in April when 12 goes live.
  - "node"

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master
  - develop

install:
 - npm install

script:
 - npm test
