version: 2.1

defaults: &defaults
  working_directory: ~/repo

jobs:
  build-linux:
    docker:
    - image: circleci/node:8.9.1

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: npm install

    - run:
        name: Run tests
        command: npm test

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - persist_to_workspace:
        root: ~/repo
        paths: .
    
  #build-macos: 
  #  macos:  
  #    xcode: "10.0.0" 
  #build-windows:
  #  executor: circleci/windows@1.0.0/vs2019
  #  steps:
  #    - checkout
  #    - run: Write-Host 'Hello, Windows'